name: CI
on: 
  - push
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: savonet/liquidsoap:v2.2.5
      options: --user root
      volumes:
        - ./:/tmp/test
    steps:
      - name: Test
        run: |
          apt-get update
          apt-get install -y --no-install-recommends ffmpeg
          ffmpeg -f lavfi -i "sine=frequency=100:duration=2" -c:a libmp3lame -b:a 16k -y 1.mp3
          find / -name 'main.liq'
          pwd
          ls -al
          liquidsoap main.liq